---
title: "Vignette"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(Bioregionalization)
library(dplyr)

```

```{r dataset}
# Example dataset with 100 sites and number of species between 1 and 10
set.seed(1)
ex <- data.frame(
  site = as.character(unlist(sapply(paste0("site", seq(1:100)),
                                    function(x) rep(x, sample(1:10, 1))))))
ex <- ex %>%
  group_by(site) %>%
  mutate(sp = sample(letters[seq(1:20)], n()), # identity of species
         ab = sample(c(1:10), n())) %>% # abundances between 1 & 10 individuals
  ungroup() %>%
  as.data.frame()

# Associate coordinates
coord <- data.frame(site = paste0("site", seq(1:100)),
                    x = seq(1, 100),
                    y = seq(1, 100))
```

The first step is to convert the data.frame into a contingency table.

```{r contingency_matrix}
sp_mat <- contingency(ex, "sp", "site", "ab", binary = TRUE)
```

We then need to project the network.

```{r projection}
sp_proj <- project_network(sp_mat, similarity = "simpson")
sp_proj <- sp_proj[, c("id1", "id2", "simpson")]

# write.table(sp_proj[, c("id1", "id2", "simpson")], "OSLOM2/vignette.txt",
#             row.names = FALSE)

```

Running OSLOM (unre Linux distribution).

Here:
./oslom_undir -r 10 -seed 1000 -t 0.5 -cp 0.5 -f vignette.txt -w

Converting the OSLOM .tp file into a list.

```{r conversion_OSLOM}
res <- readLines("OSLOM2/vignette.txt_oslo_files/tp")
oslom_vignette <- oslom_output(res, sp_mat)
```

Function to compute zscores.

Projection on a map.





